# Generated by Django 5.2.5 on 2025-09-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_branchpresident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('food', 'Food & Catering'), ('fashion', 'Fashion & Beauty'), ('technology', 'Technology'), ('education', 'Education & Training'), ('health', 'Health & Wellness'), ('automotive', 'Automotive'), ('real_estate', 'Real Estate'), ('services', 'Services'), ('other', 'Other')], max_length=20)),
                ('advertiser_name', models.CharField(max_length=100)),
                ('advertiser_contact', models.CharField(max_length=20)),
                ('advertiser_email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('is_member', models.BooleanField(default=False)),
                ('member_congregation', models.CharField(blank=True, max_length=100, null=True)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('range', 'Price Range')], default='fixed', max_length=20)),
                ('images', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
    ]
