# Generated by Django 5.2.5 on 2025-09-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='YStoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('accessories', 'Accessories'), ('books', 'Books'), ('merchandise', 'Merchandise'), ('other', 'Other')], default='merchandise', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ystore/')),
                ('is_available', models.BooleanField(default=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_ystore_item',
            },
        ),
    ]
