# Generated by Django 5.2.5 on 2025-09-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ystoreitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchpresident',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
