# Generated by Django 5.2.4 on 2025-09-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dashboard_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
