# Generated by Django 5.2.4 on 2025-09-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_dashboard_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.PositiveIntegerField(default=0, help_text='Number of participants/attendees'),
        ),
    ]
