# Generated by Django 5.2.4 on 2025-09-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.AddField(
            model_name='teammember',
            name='congregation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='quote',
            field=models.TextField(blank=True, help_text='Favorite quote or motto'),
        ),
    ]
