# Generated by Django 5.2.4 on 2025-09-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_teammember_bio_teammember_congregation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ystoreitem',
            name='contact',
            field=models.CharField(default='+233244123456', max_length=20),
        ),
    ]
