# Generated by Django 5.2.4 on 2025-09-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ystoreitem_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ystoreitem',
            name='contact',
            field=models.CharField(default='', max_length=20),
        ),
    ]
