# Generated by Django 5.2.4 on 2025-09-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_ystoreitem_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('president', 'President'), ('president_rep', "President's Representative"), ('secretary', 'Secretary'), ('assistant_secretary', 'Assistant Secretary'), ('financial_secretary', 'Financial Secretary'), ('treasurer', 'Treasurer'), ('organizing_secretary', 'Organizing Secretary'), ('evangelism_secretary', 'Evangelism Secretary'), ('welfare_secretary', 'Welfare Secretary'), ('other', 'Other')], default='other', max_length=50)),
                ('reign_period', models.CharField(help_text='e.g., 2020-2022', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='past_executives/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Past Executive',
                'verbose_name_plural': 'Past Executives',
            },
        ),
    ]
