# Generated by Django 5.2.5 on 2025-09-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ministry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministryregistration',
            name='age',
        ),
        migrations.AlterField(
            model_name='ministryregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
