# Generated by Django 5.2.5 on 2025-09-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_ministryregistration_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministryregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
