# Generated by Django 5.2.5 on 2025-09-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_ministryregistration_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='advertiser_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
