# Generated by Django 5.2.4 on 2025-09-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_advertisement_advertiser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='advertiser_contact',
            field=models.CharField(max_length=25),
        ),
    ]
