# Generated by Django 5.2.4 on 2025-09-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_update_advertiser_contact_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='advertiser_contact',
            field=models.CharField(max_length=30),
        ),
    ]
