# Generated by Django 5.2.4 on 2025-09-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_increase_advertiser_contact_to_30'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(default='GHS', max_length=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='purpose',
            field=models.CharField(choices=[('general', 'General Fund'), ('events', 'Events & Activities'), ('welfare', 'Welfare Committee'), ('ministry', 'Ministry Support'), ('building', 'Building Fund'), ('education', 'Education Fund'), ('other', 'Other')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='recurring_frequency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='verified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
