# Generated by Django 5.2.4 on 2025-09-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_update_donation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
