# Generated by Django 5.2.4 on 2025-09-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_galleryitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='congregation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
