# Generated by Django 5.2.4 on 2025-09-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_galleryitem_congregation_galleryitem_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/'),
        ),
    ]
