# Generated by Django 5.2.4 on 2025-09-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_dashboard_deleted_event_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
