# Generated by Django 5.2.4 on 2026-06-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_contribution_expense_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_text', models.TextField(default='To nurture the spiritual, moral, and social growth of young people within the Presbyterian Church by engaging them in activities that strengthen their faith and equip them for leadership and service.')),
                ('mission_image', models.ImageField(blank=True, help_text='Image for the Mission section', null=True, upload_to='mission-vision/')),
                ('vision_text', models.TextField(default='To raise a generation of spiritually grounded and socially responsible youth who actively contribute to the growth of the church and the transformation of society.')),
                ('vision_image', models.ImageField(blank=True, help_text='Image for the Vision section', null=True, upload_to='mission-vision/')),
                ('motto', models.CharField(default='YPG! Service All The Way, You! Practice Godliness', max_length=200)),
                ('theme_title', models.CharField(default='2025 Theme', max_length=200)),
                ('theme_text', models.TextField(default='Celebrating our Heritage, Persisting in Mission, Embracing our Missionary Legacy as Youth (Colossians 1:58)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vision & Mission',
                'verbose_name_plural': 'Vision & Mission',
            },
        ),
    ]
