# Generated by Django 5.2.4 on 2026-06-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_visionmission'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE core_analytics DROP COLUMN IF EXISTS quiz_participants;",
            reverse_sql="ALTER TABLE core_analytics ADD COLUMN quiz_participants INTEGER DEFAULT 0;",
        ),
    ]
