# Generated by Django 5.2.4 on 2026-06-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_dailyvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('other', 'Other')], default='other', max_length=50)),
                ('custom_platform_name', models.CharField(blank=True, help_text="Custom platform name if 'other' is selected", max_length=50)),
                ('url', models.URLField(help_text='The URL to the social media profile')),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name or custom icon identifier', max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this link is displayed on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
