# Generated by Django 5.2.4 on 2026-06-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='icon_file',
            field=models.ImageField(blank=True, help_text='Upload custom icon image', null=True, upload_to='social_media_icons/'),
        ),
    ]
