# Generated by Django 5.2.4 on 2026-06-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_socialmedialink_icon_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(blank=True, default='', max_length=200)),
                ('avatar', models.TextField(blank=True, help_text='Base64 encoded avatar image', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile Settings',
                'verbose_name_plural': 'Profile Settings',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_title', models.CharField(default='PCG Ahinsan District YPG', max_length=200)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default="Presbyterian Young People's Guild - Ahinsan District")),
                ('social_media_facebook', models.URLField(blank=True, default='')),
                ('social_media_instagram', models.URLField(blank=True, default='')),
                ('social_media_twitter', models.URLField(blank=True, default='')),
                ('social_media_youtube', models.URLField(blank=True, default='')),
                ('social_media_linkedin', models.URLField(blank=True, default='')),
                ('language', models.CharField(default='English', max_length=50)),
                ('border_radius', models.CharField(default='medium', max_length=50)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
