# Generated by Django 5.2.4 on 2026-06-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_profilesettings_websitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesettings',
            name='social_media_facebook',
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='social_media_instagram',
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='social_media_linkedin',
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='social_media_twitter',
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='social_media_youtube',
        ),
    ]
