# Generated by Django 5.2.4 on 2026-08-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
