# Generated by Django 5.2.4 on 2026-08-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_announcement_options_alter_announcement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='momo_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='momo_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
