# Generated by Django 5.2.5 on 2026-08-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_passwordchangeotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
